{
 "title": "Flink Dashboard",
 "description": "flink with prometheus",
 "tags": [ "flink" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Cluster",
    "query": "label_values(flink_jobmanager_taskSlotsTotal,job)"
   }
  ]
 },
 "panels": [
  { "title": "Slots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# of TaskManagers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(flink_jobmanager_numRegisteredTaskManagers)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "# of Running Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_numRunningJobs",
     "legendFormat": "{{instance}} jobmanager运行的job数量"
    }
   ]
  },
  {
   "title": "Taskslots available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsAvailable"
    }
   ]
  },
  {
   "title": "Taskslots total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsTotal"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "TaskManager Garbage Collection count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(flink_taskmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Count[30s])",
     "legendFormat": "{{host}}_{{tm_id}}_老年代gc count"
    },
    {
     "expr": "delta(flink_taskmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Count[30s])",
     "legendFormat": "{{host}}_{{tm_id}}_年轻代gc count"
    }
   ]
  },
  {
   "title": "TaskManagers Garbage Collection Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "delta(flink_taskmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Time[30s])",
     "legendFormat": "{{host}}_{{tm_id}}_年轻代gc时间"
    },
    {
     "expr": "delta(flink_taskmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Time[30s])",
     "legendFormat": "{{host}}_{{tm_id}}_老年代gc时间"
    }
   ]
  },
  {
   "title": "live Thread count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Threads_Count",
     "legendFormat": "{{host}} jobManager live Thread counts"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Threads_Count",
     "legendFormat": "{{host}} taskManger live Thread counts"
    }
   ]
  },
  { "title": "IO-JobManager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "JobManager Memory Available",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Max - flink_jobmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "JobManager NonHeap Memory Available",
   "type": "graph",
   "description": "JobManager NonHeap Memory Available",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_NonHeap_Committed-flink_jobmanager_Status_JVM_Memory_NonHeap_Used",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "IO-TaskManager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "TaskManager Memory Available",
   "type": "graph",
   "description": "TaskManager Memory Available",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Max-flink_taskmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "{{host}}:{{tm_id}}"
    }
   ]
  },
  {
   "title": "TaskManger NonHeap Memory Available",
   "type": "graph",
   "description": "TaskManger NonHeap Memory Available",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Committed-flink_taskmanager_Status_JVM_Memory_NonHeap_Used",
     "legendFormat": "{{host}}:{{tm_id}}"
    }
   ]
  },
  {
   "title": "BackPressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "inPoolUsag",
     "type": "graph",
     "description": "inPoolUsag",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Output_Buffers_inPoolUsage{job_name=~\"$job_name\"}",
       "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_inPoolUse"
      }
     ]
    },
    {
     "title": "outPoolUsage",
     "type": "graph",
     "description": "outPoolUsage",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_outPoolUsage{job_name=~\"$job_name\"}",
       "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_outPoolUsage"
      }
     ]
    },
    {
     "title": "outputQueueLength",
     "type": "graph",
     "description": "outputQueueLength",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_outputQueueLength{job_name=~\"$job_name\"}",
       "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_outputQueueLength"
      }
     ]
    },
    {
     "title": "numRecordsOutPerSecond",
     "type": "graph",
     "description": "numRecordsOutPerSecond",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_numRecordsOutPerSecond{job_name=~\"$job_name\"}",
       "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_RecordsOutPerSecond"
      }
     ]
    },
    {
     "title": "numRecordsInPerSecond",
     "type": "graph",
     "description": "umRecordsInPerSecond",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_numRecordsInPerSecond{job_name=~\"$job_name\"}",
       "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_RecordsInPerSecond"
      }
     ]
    },
    {
     "title": "inputQueueLength",
     "type": "graph",
     "description": "inputQueueLength",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Output_Buffers_inputQueueLength{job_name=~\"$job_name\"}",
       "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_inputQueueLength"
      }
     ]
    }
   ]
  },
  {
   "title": "CheckPoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "lastCheckpointDuration",
     "type": "graph",
     "description": "lastCheckpointDuration",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_job_lastCheckpointDuration{job_name=~\"$job_name\"}",
       "legendFormat": "{{host}}_{{job_name}}"
      }
     ]
    },
    {
     "title": "Last CheckPoint Size",
     "type": "graph",
     "description": "Last CheckPoint Size",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(flink_jobmanager_job_lastCheckpointSize{job_name=~\"$job_name\"}[2m])",
       "legendFormat": "{{host}}_{{job_name}}"
      }
     ]
    },
    {
     "title": "numberOfFailedCheckpoints",
     "type": "graph",
     "description": "numberOfFailedCheckpoints",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(flink_jobmanager_job_numberOfFailedCheckpoints{job_name=~\"$job_name\"}[2m])",
       "legendFormat": "{{host}}_{{job_name}}_FailedCheckpoints"
      }
     ]
    }
   ]
  },
  {
   "title": "connector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "offset commit failures to Kafka",
     "type": "graph",
     "description": "offset commit failures to Kafka",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_operator_commitsFailed{job_name=~\"$job_name\"}[2m])",
       "legendFormat": "{{host}}_{{job_name}}_{{tm_id}}"
      }
     ]
    },
    {
     "title": "records has dropped due to arriving late.",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_numLateRecordsDropped{job_name=~\"$job_name\"}",
       "legendFormat": "{{host}}_{{job_name}}_{{tm_id}}"
      }
     ]
    },
    {
     "title": "job-downtime",
     "type": "graph",
     "description": "job-downtime",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_job_downtime{job_name=~\"$job_name\"}",
       "legendFormat": "{{host}}_{{job_name}}_downtime"
      }
     ]
    }
   ]
  }
 ]
}